### ISSUE TITLE
incorrect data structure

### ISSUE THREAD

**Issue by xgess** [etamponi/discourse-keybase-proofs-plugin#2]
i dont think this is right: https://github.com/etamponi/discourse-keybase-proofs-plugin/blob/81a9cf16de444de0d45a22690fff6d9d9b0536df/app/controllers/proof_controller.rb#L47
here's an example of the data structure that the keybase clients and servers are expecting: https://mastodon.social/api/proofs?provider=keybase&username=xgess

**Comment by etamponi** [comment]
The tests for the controller make sure that the output is exactly the one you provided... or am I missing something?

**Comment by xgess** [comment]
ahh. i see it now. `proof.signature` is a hash of the name and sig_hash. 👍
